// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuq8pr5X-n2Vr9Zy0gyazSJajL1pqkg38',
    appId: '1:976941164854:web:5febead2a00bde132aeb97',
    messagingSenderId: '976941164854',
    projectId: 'mydailymeal-2b2ad',
    authDomain: 'mydailymeal-2b2ad.firebaseapp.com',
    storageBucket: 'mydailymeal-2b2ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIQcp0Hz-seDnYtskm7yKFcXsmlgfTM3k',
    appId: '1:976941164854:android:89b34793dc8472472aeb97',
    messagingSenderId: '976941164854',
    projectId: 'mydailymeal-2b2ad',
    storageBucket: 'mydailymeal-2b2ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrRdk9bMbWKaw98LLQyXabnKcVaZq54BU',
    appId: '1:976941164854:ios:d462f6f83bdcc0ba2aeb97',
    messagingSenderId: '976941164854',
    projectId: 'mydailymeal-2b2ad',
    storageBucket: 'mydailymeal-2b2ad.firebasestorage.app',
    iosBundleId: 'com.example.mydailymeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuq8pr5X-n2Vr9Zy0gyazSJajL1pqkg38',
    appId: '1:976941164854:web:6400011a3b8f09c12aeb97',
    messagingSenderId: '976941164854',
    projectId: 'mydailymeal-2b2ad',
    authDomain: 'mydailymeal-2b2ad.firebaseapp.com',
    storageBucket: 'mydailymeal-2b2ad.firebasestorage.app',
  );
}
