// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKubdqj06MwoZJE7wXfwFUjBD_n-QPRzc',
    appId: '1:596282069352:web:0ef461f9ed58266400c6dd',
    messagingSenderId: '596282069352',
    projectId: 'yuihatano-202405',
    authDomain: 'yuihatano-202405.firebaseapp.com',
    databaseURL: 'https://yuihatano-202405-default-rtdb.firebaseio.com',
    storageBucket: 'yuihatano-202405.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOJCN9Z3_fv6acZleCkGsPW3QDrvHVACw',
    appId: '1:596282069352:android:e1bd0bbbceadbba600c6dd',
    messagingSenderId: '596282069352',
    projectId: 'yuihatano-202405',
    databaseURL: 'https://yuihatano-202405-default-rtdb.firebaseio.com',
    storageBucket: 'yuihatano-202405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCGnc7ebNHqK5FZD9et7tSC-XMmuAQiuA',
    appId: '1:596282069352:ios:5275d438a7eeb5c400c6dd',
    messagingSenderId: '596282069352',
    projectId: 'yuihatano-202405',
    databaseURL: 'https://yuihatano-202405-default-rtdb.firebaseio.com',
    storageBucket: 'yuihatano-202405.appspot.com',
    iosBundleId: 'com.example.mydailymeal',
  );

}